fix: pass maxLength to super calls in UrlName and PathName
When calling:
```
PathName.withProject(this, 'CronMailSendNewProfileJobDescriptionNotifications', { maxLength: 255 })
```

we were getting error like:
```
Error: at /StagingEnvironment/CronSchedulerStack] Name value "AtmoskopStagingCronMailSendNewProfileJobDescriptionNotifications" is longer than the allowed limit of undefined
```

The problem was that `props?.maxLength` was not passed to the `super.WithProject`
call and this parent function then defaulted to `MAX_LENGTH_DEFAULT` (63 characters)
when calling `validateMaxLength` instead of using 255 characters as specified
by the `maxLength` option.